<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Adresses',
    'Manage' => 'Gérer',
    'Manage Contacts' => 'Gérer Les Contacts',
    'Are you sure you want to delete this item?' => '',
    'Attachments' => '',
    'Bank Account' => 'Compte',
    'Categories' => 'Catégories',
    'Configuration' => 'Configuration',
    'Contacts' => 'Contacts',
    'Create Another Contact Relation' => 'Créer une autre relation entre Contact',
    'Create Another Tag' => 'Créer un autre Tag',
    'Create Contact Relation' => 'Créer une relation entre Contact',
    'Create Tag' => 'Créer un Tag',
    'DB Backup/restore' => '',
    'Dashboard' => 'Tableau de bord',
    'Delete' => 'Supprimer',
    'Frequency' => 'Fréquence',
    'Manage Contact Relations' => 'Gérer les relations entre contacts',
    'Name' => 'Nom',
    'Orders' => 'Commandes',
    'Products' => 'Produits',
    'Record History' => 'Historique',
    'Relations' => 'Relations',
    'Reset' => 'Remettre à zéro',
    'Save' => 'Sauvegarder',
    'Search' => 'Recherche',
    'Sessions' => 'Sessions',
    'Tag ID' => 'ID de Tag',
    'Tags' => 'Tags',
    'The requested page does not exist.' => 'La page demandée n\'existe pas',
    'Transaction ID' => 'ID de transaction',
    'Transactions' => 'Transactions',
    'Update' => 'Mettre à jour',
    'Update Tag: {name}' => 'Mettre à jour: {name}',
    'Users' => 'Utilisateurs',
    'Web Shell' => 'web shell',
    'enter tags to search for...' => 'Entrez les tags à rechercher',
    'female' => 'Femme',
    'male' => 'Homme',
    'view account' => 'voir compte',
    'view contact' => 'voir contact',
    'view product' => 'voir produit',
    'Create Order' => 'Créer Commande',
    'Birthday' => 'Date de naissance',
    // placeholders
    'ex: 30/01/2019' => 'ex: 30/01/2019',
    'ex: 31/12/2020' => 'ex: 31/12/2020',
    'ex: john@gmail.com' => 'ex: jean_dupont@hotmail.com',

    'Save' => 'Sauvegarder',
    'Cancel' => 'Annuler'
];
