
GET http://localhost/dev/ws/lab/yii2-assoc/src/web/index.php?r=quality/contact/index
Accept: application/json

###

GET http://localhost/dev/ws/lab/yii2-assoc/src/web/index.php?r=quality/address/index
Accept: application/json
